# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f20551e7b3d430c1ffa7724f8e4fb2aebc2dbf0d99e7800c75cd6ada657eeba6992103c0326030b91c644d475925adbb1229fb765d6a071dd3299fa163bd633

test:
  secret_key_base: 9d870b82b98a6595955851cdb059c77f695cc0841f289589a4c8b5d9878bd38108b6e12d91b1b55e747106e14f2593d9514c7eba491a17be7304a50ae76b0c1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
